// Generated by BUCKLESCRIPT VERSION 1.6.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32");

var Most = /* module */[];

var Subject = /* module */[];

var HoldSubject = /* module */[];

var fpp = Caml_int32.div;

var x = 20;

exports.Most        = Most;
exports.Subject     = Subject;
exports.HoldSubject = HoldSubject;
exports.x           = x;
exports.fpp         = fpp;
/* No side effect */
